config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root to: "users#index"
  root to: "clients#index" # 最終的にこっちをrootページに
  devise_for :users, :controllers => {
  :registrations => 'users/registrations',
  :sessions => 'users/sessions'
  } 
  
  devise_scope :user do
    # get "user/:id", :to => "users/registrations#new"
    get "signup", :to => "users/registrations#new"
    get "login", :to => "users/sessions#new"
    get "logout", :to => "users/sessions#destroy"
  end
  
  resources :clients do
    resources :actions
    resources :affiliations
  end
  get "users" => "users#index" # 管理者のリストを表示

end

app/controllers/actions_controller.rb
class ActionsController < ApplicationController
    def index
        @client = Client.find(params[:client_id])
        @actions = Action.all.where(client_id: params[:client_id])
        if @client.nil? || @actions.nil?
            logger.debug "nilだよー"
            flash[:error] = "このクライアントには何もアクションしていません"
        end
    end

    def new
        @client = Client.find(params[:client_id])
        @action = @client.actions.new
        # binding.pry

    end

    def edit
        @client = Client.find(params[:client_id])
        @actions = Client.find(params[:client_id]).actions.find(params[:id])
    end

    def create
        @client = Client.find(params[:client_id])
        @action = @client.actions.new(set_action_params(params))
        if @action.save
            redirect_to client_actions_path(@client)
        else
            flash[:error] = "something is wrong"
            render "new"
        end
    end

    def update
        @action = Action.find(params[:id])
        if @action.update(set_action_params(params))
            redirect_to client_actions_path
        else
          # エラーの内容ってどうやって取り出す？   
          flash[:error] = "error has occurred"
          redirect_to edit_client_action_path
        end

    end
    def destroy
        @client = Client.find(params[:client_id])
        @action = Client.find(params[:client_id]).actions.find(params[:id])
        if @action.delete
            redirect_to client_actions_path(@client, @action)
        else
        end
    end

    def set_action_params(params)
        params.require(:actions).permit(:content, :state, :expectation)

    end
end

app/helpers/actions_helper.rb
module ActionsHelper
end

app/views/actions/edit.html.slim
= @client.inspect
br
div = flash[:error].inspect

= form_for :actions, url: "/clients/#{@client.id}/actions/#{@actions.id}", method: :patch do |form|
    = form.label :content 
    = form.text_field :content
    brbr
    = form.label :state

    input type="text" name="actions[state]" id="action_state"
    brbr
    = form.label :expectation
    input type="text" name="actions[expectation]" id="action_expectation"
    brbr
    = form.submit "進捗を作成dane"

app/views/actions/index.html.slim
p 「#{@client.name}」さんに対する進捗
hr

center
  table frame="box" rules="all"
    tr
      th ID
      th 内容
      th 状態
      th 期待値
      th 編集リンク
      th 削除リンク
      th 作成日
      th 更新日
    - @actions.each do |action|
      tr
        td = action.id
        td = action.content
        td = action.state.empty? ? "なし" : action.state
        td = action.expectation.empty? ? "なし" : action.expectation
        td = link_to "Edit", edit_client_action_path(@client, action)
        td = link_to "Destroy", client_action_path(@client, action), method: :delete, data: { confirm: 'Are you sure?' }
        td = action.created_at.strftime('%Y-%m-%d')
        td = action.updated_at.strftime('%Y-%m-%d')
  hr
  br
  = link_to "進捗を追加する", new_client_action_path(@client)
  br

  = link_to "クラアントのリストを表示する", root_path 

app/views/actions/new.html.slim
=flash[:error]

/ = form_for :actions, url: "/clients/#{@client.id}/actions/create", method: :post do |form|
= form_for :actions, url: client_actions_path(@client.id), method: :post do |form|
    = form.label :content 
    = form.text_field :content
    brbr
    = form.label :state

    input type="text" name="actions[state]" id="action_state"
    brbr
    = form.label :expectation
    input type="text" name="actions[expectation]" id="action_expectation"
    brbr
    = form.submit "進捗を作成"