config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root to: "users#index"
  root to: "clients#index" # 最終的にこっちをrootページに
  devise_for :users, :controllers => {
  :registrations => 'users/registrations',
  :sessions => 'users/sessions'
  } 
  
  devise_scope :user do
    # get "user/:id", :to => "users/registrations#new"
    get "signup", :to => "users/registrations#new"
    get "login", :to => "users/sessions#new"
    get "logout", :to => "users/sessions#destroy"
  end
  
  resources :clients do
    resources :actions
    resources :affiliations
  end
  get "users" => "users#index" # 管理者のリストを表示

end

app/models/client.rb
class Client < ApplicationRecord
    has_many :actions, dependent: :destroy
    has_many :affiliations, dependent: :destroy

    validates :name, presence: true
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :authenticate_user!
  def index
    keyword=params[:keyword]
    if keyword.present?
      # キーワドを含む所属を検索 所属からクライアントIDを取得
      @clients = Client.joins(:affiliations).where("affiliations.name like ?", "%#{keyword}%").page(params[:page])
    else
      @clients = Client.all.page(params[:page])
    end
    
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.new(clients_params(params))
    if @client.save
      redirect_to @client
    else
      flash[:error] = 'Errorですよ'
      render "new"
    end
  end

  def show
    @client = Client.find(params[:id])
  end

  def edit
    @client = Client.find(params[:id])
  end

  def update
    @client = Client.find(params[:id])
    if @client.update(clients_params(params))
        redirect_to @client
    else
      render "new"
    end
  end

  def destroy
    @client= Client.find(params[:id])
    if @client.destroy
      flash[:success] = "Destroyed successfully"
      redirect_to root_path
    else
      flash[:error] = "Failed to destroy"
      redirect_to :root
    end
  end

  def clients_params(params)
    params.require(:client).permit(:name, :email, :position)
  end
end

app/helpers/client_helper.rb
module ClientHelper
end

app/views/clients/edit.html.slim
=flash[:error] unless flash.nil?
br
center
  = form_with model: @client do |form|
    
    = form.label :name
    br
    = form.text_field :name
    br
    = form.label :email
    br
    = form.text_field :email
    br
    = form.label :position 
    br
    = form.text_field :position
    br
    = form.submit
    br

app/views/clients/index.html.slim
= render "users/header"
br

div.container-fluid
  div class="row"
    div class="col-md-9"
      center
        center
          = form_tag(root_path, method: "get")
            input type="text" name="keyword"
            button type = "submit" 検索

            
        p クライアントをクリックで過去のアクションを表示
        table rules="all" frame="box"
          thead
            tr
              th ID
              th Name
              th
              th
              th
        
          tbody
            - @clients.each do |client|
              tr
                td = client.id
                td = link_to client.name, client_actions_path(client)
                td = link_to 'Show', client_path(client)
                td = link_to 'Edit', edit_client_path(client)
                td = link_to 'Destroy', client_path(client), method: :delete, data: { confirm: 'Are you sure?' }
        
        div.container
          = paginate(@clients)

    div class="col-md-3" 
      = link_to "新しいクライアントを作成", new_client_path
      / = link_to "新しい所属を作成", client_affiliations_path

/ トータルが12じゃないと改行される
hr

app/views/clients/new.html.slim
= flash[:error] unless flash[:error].nil?
br
center
  = form_with model: @client do |form|
    = form.label :name
    br
    = form.text_field :name
    br
    = form.label :email
    br
    = form.text_field :email
    br
    = form.label :position
    br
    = form.text_field :position
    br
    = form.submit
    br

app/views/clients/show.html.slim
center
  table frame= "box" rules="all"
      thead
          tr
              th ID
              th 名前
              th ポジション
              th メールアドレス
      tbody
          tr
              td = @client.id
              td = @client.name
              td = @client.position
              td = @client.email
  
hr
= link_to "所属を表示", client_affiliations_path(@client)
br
= link_to "クライアントのリストを表示", clients_path