config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root to: "users#index"
  root to: "clients#index" # 最終的にこっちをrootページに
  devise_for :users, :controllers => {
  :registrations => 'users/registrations',
  :sessions => 'users/sessions'
  } 
  
  devise_scope :user do
    # get "user/:id", :to => "users/registrations#new"
    get "signup", :to => "users/registrations#new"
    get "login", :to => "users/sessions#new"
    get "logout", :to => "users/sessions#destroy"
  end
  
  resources :clients do
    resources :actions
    resources :affiliations
  end
  get "users" => "users#index" # 管理者のリストを表示

end

app/models/affiliation.rb
class Affiliation < ApplicationRecord
    belongs_to :clients, optional: true

    validates :name, presence: true
    validates :client_id, presence: true
    
end

app/controllers/affiliations_controller.rb
class AffiliationsController < ApplicationController
    # beforeアクションでget_client_id的なのが必要？ そうじゃないとランダムに消せるようになってしまわない?
    def index
        @client = Client.find(params[:client_id])
        @affiliations= @client.affiliations
    end

    def new
        @client = Client.find(params[:client_id])
        @affiliation = @client.affiliations.new
    end

    def create
        @client = Client.find(params[:client_id])
        @affiliation = @client.affiliations.new(affiliation_params(params))
        if @affiliation.save
            redirect_to client_affiliations_path(@client)
        else
            flash[:error] = 'Errorだよ'
            # redirect_to new_client_affiliation_path
            # render "new", {affiliation: @affiliation}
            render "new"
        end
    end

    def edit
        @client = Client.find(params[:client_id])
        @affiliation = Affiliation.find(params[:id]) if params[:aff].nil?

    end

    def update
        @client = Client.find(params[:client_id])
        @affiliation = Affiliation.find(params[:id])
        if @affiliation.update(affiliation_params(params))
            redirect_to client_affiliations_path(client_id: params[:client_id]), success: 'Item was successfully updated.'
        else
            params[:aff] = @affiliation
            flash[:error] = "Failed to update"
            # render "edit"
            # redirect_to edit_client_affiliation_path(id: params[:id]), error: 'Failed to update2.', affiliation: @affiliation
            redirect_to edit_client_affiliation_url(id: params[:id]), error: 'Failed to update2.'
        end
    end

    def destroy
      @affiliation = Client.find(params[:client_id]).affiliations.find(params[:id])
      if @affiliation.destroy
        flash[:success] = "Destroyed successfully"
        redirect_to root_path
      else
        flash[:error] = "Failed to destroy"
        redirect_to :root
      end


    end

    def show
        @affiliation = Client.find(params[:client_id]).affiliations.find(params[:id])
    end

    def affiliation_params(params)
        params.require(:affiliation).permit(:name, :address, :call, :email, :memo)
    end
end

app/helpers/affiliations_helper.rb
module AffiliationsHelper
end

app/views/affiliations/edit.html.slim
= flash[:error]
br
= @affiliation.errors.inspect unless @affiliation.errors.nil?
br

/ = form_for :affiliations, url: client_affiliations_path(@client.id), method: :post do |form|
/ = form_for [@client, @affiliation], method: :patch do |form|
center
  = simple_form_for [@client, @affiliation], method: :patch do |form|
      = form.label :name
      = form.error :name
      br
      = form.text_field :name
      br
      = form.label :address
      br
      = form.text_field :address
      br
      = form.label :call
      br
      = form.text_field :call
      br
      = form.label :email
      br
      = form.text_field :email
      br
      = form.label :memo
      br
      = form.text_field :memo
      br
      = form.submit "所属を編集する"

app/views/affiliations/index.html.slim
= render "users/header"
br

center style="padding:5em;border: 1px dotted #333333;"
  - if !@affiliations.empty?
    table frame="box" rules="all"
      thead
        tr
          th ID
          th 名前
          th 住所
          th 電話
          th メール
          th メモ
          th 作成日
          th 更新日
          th 変更
          th 削除
      tbody
          - @affiliations.each do |aff|
            / = aff.inspect
            tr
              td = aff.id
              td = link_to aff.name, client_affiliation_path(@client, aff)
              td = aff.address
              td = aff.call
              td = aff.email
              td = aff.memo
              td = aff.created_at
              td = aff.updated_at
              td =link_to "Edit", edit_client_affiliation_path(@client, aff)
              td =link_to "Delete", client_affiliation_path(@client, aff), method: :delete, data: { confirm: 'Are you sure?' }
  - else
    p 所属先はありません
  
  br
  div class="btn btn-warning" = link_to "新しい所属先を作成", new_client_affiliation_path
  / br
  / div class="btn btn-warning" = link_to "クライアント一覧", root_path

app/views/affiliations/new.html.slim
= flash[:error]
br
= @affiliation.errors.inspect unless @affiliation.errors.nil?
br

/ = form_for :affiliations, url: client_affiliations_path(@client.id), method: :post do |form|
= form_for [@client, @affiliation], method: :post do |form|
    = form.label :name
    br
    = form.text_field :name
    br
    = form.label :address
    br
    = form.text_field :address
    br
    = form.label :call
    br
    = form.text_field :call
    br
    = form.label :email
    br
    = form.text_field :email
    br
    = form.label :memo
    br
    = form.text_field :memo
    br
    = form.submit "所属を作成する"

app/views/affiliations/show.html.slim
p "showだよ"

= @affiliation.inspect

hr
= link_to "ルートパスに戻る", root_path